# Generated by Django 4.2.2 on 2023-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_slug_alter_blog_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=221, null=True, unique_for_date='created_date'),
        ),
    ]
