# Generated by Django 4.2.2 on 2023-06-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_travel_blog_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subblog',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('is_vide', models.BooleanField(default=False)),
                ('sub_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subblog')),
            ],
        ),
    ]
