# Generated by Django 4.2.2 on 2023-06-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='top_level_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
